services:
  postgres_mafacture:
    image: postgres:latest
    container_name: postgres_mafacture
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${SHOP_DB_NAME}
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: mafacture
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      - postgres_mafacture
    command: sh -c "npx prisma migrate deploy && npm run build && npm run start:prod"
    ports:
      - '3000:3000'
    links:
      - postgres_mafacture

volumes:
  postgres-data:
